# Generated by Django 4.2.1 on 2023-05-12 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeekPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('rank', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('status', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32)),
            ],
            bases=('scheduler.basemodel',),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('venue_id', models.CharField(max_length=32)),
                ('reservation_type', models.CharField(max_length=32)),
                ('venue_name', models.CharField(max_length=64, null=True)),
                ('display_name', models.CharField(max_length=64, null=True)),
                ('res_platform', models.IntegerField(choices=[(0, 'Tock'), (1, 'Resy'), (3, 'Opentable')])),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('scheduler.basemodel',),
        ),
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('log', models.TextField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.reservationrequest')),
            ],
            bases=('scheduler.basemodel',),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='booked_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.venue'),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DecisionPreferences',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='scheduler.basemodel')),
                ('active', models.BooleanField(default=True)),
                ('ideal_time', models.CharField(max_length=16)),
                ('days_of_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scheduler.dayofweekpreference')),
                ('specific_date_flag', models.BooleanField(default=False)),
                ('specific_date', models.DateField()),
                ('threshold', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scheduler.basemodel',),
        ),
    ]
