# Generated by Django 4.2.1 on 2023-05-12 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPreference',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('active', models.BooleanField(default=True)),
                ('ideal_time', models.CharField(max_length=16)),
                ('specific_date_flag', models.BooleanField(default=False)),
                ('specific_date', models.DateField()),
                ('threshold', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scheduler.basemodel',),
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='active',
        ),
        migrations.DeleteModel(
            name='DecisionPreferences',
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.decisionpreference'),
        ),
    ]
