# Generated by Django 4.2.1 on 2023-05-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_decisionpreference_remove_dayofweekpreference_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
