# Generated by Django 4.2.1 on 2023-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_venue_display_name_alter_venue_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservation_type',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
