# Generated by Django 4.2.1 on 2023-06-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_reservationrequest_active_runhistory_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='rank',
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='fri_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='mon_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='sat_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='sun_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='thu_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='tue_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayofweekpreference',
            name='wed_rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='daily_preferences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.dayofweekpreference'),
        ),
    ]
