# Generated by Django 4.2.1 on 2023-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_dayofweekpreference_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayofweekpreference',
            name='display_name',
            field=models.CharField(default='hello', max_length=32),
            preserve_default=False,
        ),
    ]
