# Generated by Django 4.2.1 on 2023-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_dayofweekpreference_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='fri_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='mon_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='sat_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='sun_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='thu_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='tue_rank',
        ),
        migrations.RemoveField(
            model_name='dayofweekpreference',
            name='wed_rank',
        ),
        migrations.RemoveField(
            model_name='decisionpreference',
            name='daily_preferences',
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='fri_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='mon_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='sat_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='sun_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='thu_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='tue_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisionpreference',
            name='wed_rank',
            field=models.IntegerField(default=0),
        ),
    ]
