# Generated by Django 4.2.1 on 2023-06-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_dayofweekpreference_fri_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='decision_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.decisionpreference'),
        ),
    ]
