# Generated by Django 4.2.1 on 2023-06-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_reservationrequest_decision_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='confirmation',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
