# Generated by Django 4.2.1 on 2023-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_reservationrequest_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='confirmation',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
