# Generated by Django 4.2.1 on 2023-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_alter_reservationrequest_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionpreference',
            name='display_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
