# Generated by Django 4.2.1 on 2023-06-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0012_decisionpreference_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('resy_api_key', models.CharField(blank=True, max_length=128)),
                ('resy_auth_token', models.CharField(blank=True, max_length=512)),
                ('resy_payment_id', models.CharField(blank=True, max_length=32)),
                ('tock_email', models.CharField(blank=True, max_length=128)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scheduler.basemodel',),
        ),
    ]
