# Generated by Django 4.2.1 on 2023-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_accountinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='display_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.accountinfo'),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='party_size',
            field=models.IntegerField(default=2),
        ),
    ]
