# Generated by Django 4.2.1 on 2024-06-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0014_accountinfo_display_name_reservationrequest_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingPreference',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scheduler.basemodel')),
                ('display_name', models.CharField(blank=True, max_length=32)),
                ('frequency', models.IntegerField(choices=[(0, 'Hourly'), (1, 'Daily')])),
                ('mon_run', models.BooleanField(default=True)),
                ('tue_run', models.BooleanField(default=True)),
                ('wed_run', models.BooleanField(default=True)),
                ('thu_run', models.BooleanField(default=True)),
                ('fri_run', models.BooleanField(default=True)),
                ('sat_run', models.BooleanField(default=True)),
                ('sun_run', models.BooleanField(default=True)),
                ('specific_time', models.TimeField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scheduler.basemodel',),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='scheduling_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.schedulingpreference'),
        ),
    ]
