# Generated by Django 4.2.1 on 2024-06-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_schedulingpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingpreference',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedulingpreference',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
