# Generated by Django 4.2.1 on 2024-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_schedulingpreference_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='last_run',
            field=models.DateTimeField(null=True),
        ),
    ]
