# Generated by Django 4.2.1 on 2024-07-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_reservationrequest_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
