# Generated by Django 4.2.1 on 2024-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_accountinfo_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservation_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
