# Generated by Django 4.2.1 on 2024-07-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_alter_venue_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tock_multiple_res_types',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='tock_type_to_select',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
