# Generated by Django 4.2.1 on 2024-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_alter_schedulingpreference_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='res_platform',
            field=models.IntegerField(choices=[(0, 'Tock'), (1, 'Resy'), (2, 'Resy Selenium'), (3, 'Opentable')]),
        ),
    ]
