# Generated by Django 4.2.1 on 2024-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_alter_venue_res_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='resy_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
